##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  spring配置  ###################
spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:com/example/dao/repository/mapping/*.xml #mapper-locations 这个是你定义的mapping文件，支持通配符，如果有多个用逗号隔开。
  type-aliases-package: com.example.dao.entity #这个定义实体类所在的包名，或者其他能使用别名的类所在的包。
  global-config:
    id-type: 0 # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazy-loading-enabled: true #延时加载的开关
    multiple-result-sets-enabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pos?useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password:

logging:
  level:
    ROOT: info
    com:
      example: debug
  file: /Users/luox/Desktop/logs/app-mybatis.log


---

#####################################################################
########################  测试环境profile  ##########################
#####################################################################

spring:
  profiles: test
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/pos?useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
      username: root
      password:

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: /Users/luox/Desktop/logs/app-mybatis.log



