##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  spring配置  ###################
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/iou?serverTimezone=UTC
    username: root
    password: 1234

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
  typeAliasesPackage: >
    com.example.domain
  global-config:
    id-type: 0  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

logging:
  level:
    org.springframework.web.servlet: ERROR

---

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev
  cache:
    type: REDIS
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    database: 0
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 8
      min-idle: 0
    password: 1234

logging:
  level:
    ROOT: INFO
    com:
      xncoding: DEBUG
  file: /home/luox/Documents/log/app.log

# 项目名称、版本、版权年份
ruoyi:
  name: luoxiang
  version: 2.0.0
  copyrightYear: 2018
  profile: D:/profile/

# 代码生成
gen:
  # 作者
  author: luoxiang
  # 默认生成包路径 module 需改成自己的模块名称 如 system monitor tool
  packageName: com.demo.project.module
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀(类名不会包含表前缀)
  tablePrefix: sys_